import {
  curveBasis,
  curveBasisClosed,
  curveBasisOpen,
  curveBundle,
  curveCardinal,
  curveCardinalClosed,
  curveCardinalOpen,
  curveCatmullRom,
  curveCatmullRomClosed,
  curveCatmullRomOpen,
  curveLinear,
  curveLinearClosed,
  curveMonotoneX,
  curveMonotoneY,
  curveNatural,
  curveStep,
  curveStepAfter,
  curveStepBefore,
} from 'd3';

export default {
  Basis: curveBasis,
  BasisClosed: curveBasisClosed,
  BasisOpen: curveBasisOpen,
  Bundle: curveBundle,
  Cardinal: curveCardinal,
  CardinalClosed: curveCardinalClosed,
  CardinalOpen: curveCardinalOpen,
  CatmullRom: curveCatmullRom,
  CatmullRomClosed: curveCatmullRomClosed,
  CatmullRomOpen: curveCatmullRomOpen,
  Linear: curveLinear,
  LinearClosed: curveLinearClosed,
  MonotoneX: curveMonotoneX,
  MonotoneY: curveMonotoneY,
  Natural: curveNatural,
  Step: curveStep,
  StepAfter: curveStepAfter,
  StepBefore: curveStepBefore,
};
