import {
  easeBack,
  easeBackIn,
  easeBackInOut,
  easeBackOut,
  easeBounce,
  easeBounceIn,
  easeBounceInOut,
  easeBounceOut,
  easeCircle,
  easeCircleIn,
  easeCircleInOut,
  easeCircleOut,
  easeCubic,
  easeCubicIn,
  easeCubicInOut,
  easeCubicOut,
  easeExp,
  easeExpIn,
  easeExpInOut,
  easeExpOut,
  easeLinear,
  easePolyIn,
  easePolyInOut,
  easePolyOut,
  easeQuad,
  easeQuadIn,
  easeQuadInOut,
  easeQuadOut,
  easeSin,
  easeSinIn,
  easeSinInOut,
  easeSinOut,
} from 'd3';

export default {
  'back': easeBack,
  'back-in': easeBackIn,
  'back-in-out': easeBackInOut,
  'back-out': easeBackOut,
  'bounce': easeBounce,
  'bounce-in': easeBounceIn,
  'bounce-in-out': easeBounceInOut,
  'bounce-out': easeBounceOut,
  'circle': easeCircle,
  'circle-in': easeCircleIn,
  'circle-in-out': easeCircleInOut,
  'circle-out': easeCircleOut,
  'cubic': easeCubic,
  'cubic-in': easeCubicIn,
  'cubic-in-out': easeCubicInOut,
  'cubic-out': easeCubicOut,
  'exp': easeExp,
  'exp-in': easeExpIn,
  'exp-in-out': easeExpInOut,
  'exp-out': easeExpOut,
  'linear': easeLinear,
  'poly-in': easePolyIn,
  'poly-in-out': easePolyInOut,
  'poly-out': easePolyOut,
  'quad': easeQuad,
  'quad-in': easeQuadIn,
  'quad-in-out': easeQuadInOut,
  'quad-out': easeQuadOut,
  'sin': easeSin,
  'sin-in': easeSinIn,
  'sin-in-out': easeSinInOut,
  'sin-out': easeSinOut,
};
